services:
  db:
    image: postgres:16
    container_name: locker_db
    environment:
      POSTGRES_USER: locker
      POSTGRES_PASSWORD: locker
      POSTGRES_DB: locker
    ports:
      - "5433:5432"
    volumes:
      - locker_pgdata:/var/lib/postgresql/data

volumes:
  locker_pgdata:
